# Copyright (c) 2023, ANTOBOT LTD.
# All rights reserved.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# # # Code Description: This example configuration file includes robot specific information. Make a copy of this file in the 
#                       same directory (antobot_description/config) with file name of platform_config.yaml
#                       This file is included in github repository.

# Author:       soyoung.kim@antobot.ai
# # # #  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

## High-level configuration
mileage_path: "/home/antobot/Documents/mileage/"
log_path: "/home/antobot/Documents/data/logs"

robot_hardware: False
robot_platform: "ant"   # Could be "ant" or "dog"
robot_version: 4
robot_role: "UV"
location: "uk"

aRCU_enable: False
isolated_cpu: False

## Sensor information

lidar:   # please refer to lidar_config_example.yaml in the same directory for lidar configuration examples.
  1:
    type: cx
    px: 0.683
    py: 0.088
    pz: 0.75
    r: 0
    p: 0
    y: 2.35
    mode: "navigation"
    location: "front"

    device_ip: 192.168.1.200 
    device_id: 200 

gps:
  urcu:  #or f9p_usb or movingbase or urcu
    px: 0.683
    py: 0.08
    pz: 0.75
    r: 0
    p: 0
    y: 0
    mode: "navigation"

    device_port: "/dev/ttyTHS1"  #or /dev/ttyUSB* for basestation *new for urcu1.5: sudo busybox devmem 0x02430068 w 0x004
    rtk_type: "ant_mqtt"   #ppp or ntrip or ant_mqtt


imu:
  bno:
    px: -0.1146
    py: -0.01941
    pz: 0.1832
    r: 0
    p: 0
    y: 0
    mode: "navigation"
    switch: True
  icm:
    px: -0.1146
    py: -0.01941
    pz: 0.1832
    r: 0
    p: 0
    y: 0
    mode: "record"
    switch: False
  
teleop:  
  joystick: "LogitechF710"   # "LogitechF710", "Microzone6CMINI", "Pocket"
  keyboard: True