# Copyright (c) 2023, ANTOBOT LTD.
# All rights reserved.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# # # Code Description: This example configuration file includes robot specific information. Make a copy of this file in the 
#                       same directory (antobot_description/config) with file name of platform_config.yaml
#                       This file is included in github repository.

# Author:       soyoung.kim@antobot.ai
# # # #  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

## High-level configuration
mileage_path: "/home/danielfreer/Documents/mileage/"
log_path: "/home/danielfreer/Documents/data/antobot_manager_supervisor/logs"

robot_hardware: False
robot_platform: "ant"   # Could be "ant" or "dog"
robot_version: 4
robot_role: "UV"
location: "uk"
pathFollower: True
wallFollower: False
aRCU_enable: False
isolated_cpu: False
lio_enable: False
dualMid360: False

#imu_compensated_frame: False # set this value to False if the imu in URCU is faulty and showing imu drift


## Sensor information

lidar:   # please refer to lidar_config_example.yaml in the same directory for lidar configuration examples.
  1:
    type: mid360
    px: 0.683
    py: 0.0
    pz: 1.1
    r: 0
    p: 0
    y: 2.35
    mode: "navigation"
    location: "front"

    device_ip: 192.168.1.200 
    device_id: 200 

camera:
  zed:
    # need to be updated
    px: 0.683
    py: 0.0
    pz: 1.1
    r: 0
    p: 0
    y: 2.35

    mode: "recording"
    location: "left"

    device_ip: 192.168.1.103

  RP:
    # need to be updated
    px: 0.683
    py: 0.0
    pz: 1.1
    r: 0
    p: 0
    y: 2.35

    mode: "recording"
    location: "left"

    device_ip: 192.168.1.105

gps:
  urcu:  #or f9p_usb or movingbase or urcu
    px: 0.683
    py: 0.0
    pz: 1.41
    r: 0
    p: 0
    y: 0
    mode: "navigation"

    device_port: "/dev/ttyTHS1"  #or /dev/ttyUSB* for basestation *new for urcu1.5: sudo busybox devmem 0x02430068 w 0x004
    rtk_type: "ntrip"   #ppp or ntrip or ant_mqtt


imu:
  bno:
    px: -0.1146
    py: -0.01941
    pz: 0.1832
    r: 0
    p: 0
    y: 0
    mode: "navigation"
    switch: True
  xsens:
    px: 0
    py: 0
    pz: 0
    r: 0
    p: 0
    y: 0
    mode: "record"
    switch: False
  icm:
    px: -0.1146
    py: -0.01941
    pz: 0.1832
    r: 0
    p: 0
    y: 0
    mode: "record"
    switch: False
  ahrs:
    px: -0.1146
    py: -0.01941
    pz: 0.1832
    r: 0
    p: 0
    y: 0
    mode: "record"
    switch: False
    
uvpanel: 
  model: "cleanlight"
  quantity: 8
  power_each: 20
  
teleop:  
  joystick: "LogitechF710"   # "LogitechF710", "Microzone6CMINI", "Pocket"
  keyboard: False
