set(_CATKIN_CURRENT_PACKAGE "antobot_description")
set(antobot_description_VERSION "0.0.0")
set(antobot_description_MAINTAINER "Will <william.eaton@antobot.ai>")
set(antobot_description_PACKAGE_FORMAT "2")
set(antobot_description_BUILD_DEPENDS "urdf" "xacro")
set(antobot_description_BUILD_EXPORT_DEPENDS "urdf" "xacro")
set(antobot_description_BUILDTOOL_DEPENDS "catkin")
set(antobot_description_BUILDTOOL_EXPORT_DEPENDS )
set(antobot_description_EXEC_DEPENDS "urdf" "xacro")
set(antobot_description_RUN_DEPENDS "urdf" "xacro")
set(antobot_description_TEST_DEPENDS )
set(antobot_description_DOC_DEPENDS )
set(antobot_description_URL_WEBSITE "")
set(antobot_description_URL_BUGTRACKER "")
set(antobot_description_URL_REPOSITORY "")
set(antobot_description_DEPRECATED "")