set(_CATKIN_CURRENT_PACKAGE "antobot_joystick_teleop")
set(antobot_joystick_teleop_VERSION "0.0.0")
set(antobot_joystick_teleop_MAINTAINER "Daniel Freer <daniel.freer@antobot.ai>")
set(antobot_joystick_teleop_PACKAGE_FORMAT "2")
set(antobot_joystick_teleop_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "joy")
set(antobot_joystick_teleop_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "joy")
set(antobot_joystick_teleop_BUILDTOOL_DEPENDS "catkin")
set(antobot_joystick_teleop_BUILDTOOL_EXPORT_DEPENDS )
set(antobot_joystick_teleop_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "joy")
set(antobot_joystick_teleop_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "joy")
set(antobot_joystick_teleop_TEST_DEPENDS )
set(antobot_joystick_teleop_DOC_DEPENDS )
set(antobot_joystick_teleop_URL_WEBSITE "")
set(antobot_joystick_teleop_URL_BUGTRACKER "")
set(antobot_joystick_teleop_URL_REPOSITORY "")
set(antobot_joystick_teleop_DEPRECATED "")