set(_CATKIN_CURRENT_PACKAGE "antobot_ekf")
set(antobot_ekf_VERSION "0.0.0")
set(antobot_ekf_MAINTAINER "aswathi <aswathi.muralidharan@antobot.ai>")
set(antobot_ekf_PACKAGE_FORMAT "2")
set(antobot_ekf_BUILD_DEPENDS "nav_msgs" "sensor_msgs" "std_msgs" "tf2" "tf2_geometry_msgs" "tf2_ros")
set(antobot_ekf_BUILD_EXPORT_DEPENDS "nav_msgs" "sensor_msgs" "std_msgs" "tf2" "tf2_geometry_msgs" "tf2_ros")
set(antobot_ekf_BUILDTOOL_DEPENDS "catkin")
set(antobot_ekf_BUILDTOOL_EXPORT_DEPENDS )
set(antobot_ekf_EXEC_DEPENDS "nav_msgs" "sensor_msgs" "std_msgs" "tf2" "tf2_geometry_msgs" "tf2_ros")
set(antobot_ekf_RUN_DEPENDS "nav_msgs" "sensor_msgs" "std_msgs" "tf2" "tf2_geometry_msgs" "tf2_ros")
set(antobot_ekf_TEST_DEPENDS )
set(antobot_ekf_DOC_DEPENDS )
set(antobot_ekf_URL_WEBSITE "")
set(antobot_ekf_URL_BUGTRACKER "")
set(antobot_ekf_URL_REPOSITORY "")
set(antobot_ekf_DEPRECATED "")