set(_CATKIN_CURRENT_PACKAGE "antobot_safety")
set(antobot_safety_VERSION "0.0.0")
set(antobot_safety_MAINTAINER "Daniel Freer <daniel.freer@antobot.ai>")
set(antobot_safety_PACKAGE_FORMAT "1")
set(antobot_safety_BUILD_DEPENDS "roscpp" "nodelet" "dynamic_reconfigure" "pluginlib" "geometry_msgs" "yaml-cpp" "antobot_msgs")
set(antobot_safety_BUILD_EXPORT_DEPENDS "roscpp" "geometry_msgs" "pluginlib" "nodelet" "dynamic_reconfigure" "yaml-cpp" "antobot_msgs")
set(antobot_safety_BUILDTOOL_DEPENDS "catkin")
set(antobot_safety_BUILDTOOL_EXPORT_DEPENDS )
set(antobot_safety_EXEC_DEPENDS "roscpp" "geometry_msgs" "pluginlib" "nodelet" "dynamic_reconfigure" "yaml-cpp" "antobot_msgs")
set(antobot_safety_RUN_DEPENDS "roscpp" "geometry_msgs" "pluginlib" "nodelet" "dynamic_reconfigure" "yaml-cpp" "antobot_msgs")
set(antobot_safety_TEST_DEPENDS )
set(antobot_safety_DOC_DEPENDS )
set(antobot_safety_URL_WEBSITE "http://ros.org/wiki/yocs_cmd_vel_mux")
set(antobot_safety_URL_BUGTRACKER "https://github.com/yujinrobot/yujin_ocs/issues")
set(antobot_safety_URL_REPOSITORY "https://github.com/yujinrobot/yujin_ocs")
set(antobot_safety_DEPRECATED "")