set(_CATKIN_CURRENT_PACKAGE "antobot_gazebo")
set(antobot_gazebo_VERSION "0.0.1")
set(antobot_gazebo_MAINTAINER "Will <william.eaton@antobot.ai>")
set(antobot_gazebo_PACKAGE_FORMAT "1")
set(antobot_gazebo_BUILD_DEPENDS "urdf" "xacro")
set(antobot_gazebo_BUILD_EXPORT_DEPENDS "urdf" "xacro" "hector_gazebo_plugins" "gazebo_ros")
set(antobot_gazebo_BUILDTOOL_DEPENDS "catkin")
set(antobot_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(antobot_gazebo_EXEC_DEPENDS "urdf" "xacro" "hector_gazebo_plugins" "gazebo_ros")
set(antobot_gazebo_RUN_DEPENDS "urdf" "xacro" "hector_gazebo_plugins" "gazebo_ros")
set(antobot_gazebo_TEST_DEPENDS )
set(antobot_gazebo_DOC_DEPENDS )
set(antobot_gazebo_URL_WEBSITE "")
set(antobot_gazebo_URL_BUGTRACKER "")
set(antobot_gazebo_URL_REPOSITORY "")
set(antobot_gazebo_DEPRECATED "")