set(_CATKIN_CURRENT_PACKAGE "antobot_msgs")
set(antobot_msgs_VERSION "0.0.1")
set(antobot_msgs_MAINTAINER "Daniel Freer <daniel.freer@antobot.ai>")
set(antobot_msgs_PACKAGE_FORMAT "1")
set(antobot_msgs_BUILD_DEPENDS "roscpp" "serial" "std_msgs" "message_generation")
set(antobot_msgs_BUILD_EXPORT_DEPENDS "roscpp" "message_runtime" "serial" "std_msgs")
set(antobot_msgs_BUILDTOOL_DEPENDS "catkin")
set(antobot_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(antobot_msgs_EXEC_DEPENDS "roscpp" "message_runtime" "serial" "std_msgs")
set(antobot_msgs_RUN_DEPENDS "roscpp" "message_runtime" "serial" "std_msgs")
set(antobot_msgs_TEST_DEPENDS )
set(antobot_msgs_DOC_DEPENDS )
set(antobot_msgs_URL_WEBSITE "")
set(antobot_msgs_URL_BUGTRACKER "")
set(antobot_msgs_URL_REPOSITORY "/")
set(antobot_msgs_DEPRECATED "")