set(_CATKIN_CURRENT_PACKAGE "antobot_tel")
set(antobot_tel_VERSION "0.0.0")
set(antobot_tel_MAINTAINER "Daniel Freer <daniel.freer@antobot.ai>")
set(antobot_tel_PACKAGE_FORMAT "2")
set(antobot_tel_BUILD_DEPENDS "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs")
set(antobot_tel_BUILD_EXPORT_DEPENDS "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs")
set(antobot_tel_BUILDTOOL_DEPENDS "catkin")
set(antobot_tel_BUILDTOOL_EXPORT_DEPENDS )
set(antobot_tel_EXEC_DEPENDS "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs")
set(antobot_tel_RUN_DEPENDS "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs")
set(antobot_tel_TEST_DEPENDS )
set(antobot_tel_DOC_DEPENDS )
set(antobot_tel_URL_WEBSITE "")
set(antobot_tel_URL_BUGTRACKER "")
set(antobot_tel_URL_REPOSITORY "")
set(antobot_tel_DEPRECATED "")