set(_CATKIN_CURRENT_PACKAGE "antobot_heading")
set(antobot_heading_VERSION "0.0.0")
set(antobot_heading_MAINTAINER "So-Young Kim <soyoung.kim@antobot.ai>")
set(antobot_heading_PACKAGE_FORMAT "2")
set(antobot_heading_BUILD_DEPENDS "nav_msgs" "roscpp" "std_msgs" "sensor_msgs" "std_srvs" "tf2" "geonav_transform" "tf2_geometry_msgs")
set(antobot_heading_BUILD_EXPORT_DEPENDS "nav_msgs" "roscpp" "std_msgs" "sensor_msgs" "std_srvs" "tf2" "geonav_transform" "tf2_geometry_msgs")
set(antobot_heading_BUILDTOOL_DEPENDS "catkin")
set(antobot_heading_BUILDTOOL_EXPORT_DEPENDS )
set(antobot_heading_EXEC_DEPENDS "nav_msgs" "roscpp" "std_msgs" "sensor_msgs" "std_srvs" "tf2" "geonav_transform" "tf2_geometry_msgs")
set(antobot_heading_RUN_DEPENDS "nav_msgs" "roscpp" "std_msgs" "sensor_msgs" "std_srvs" "tf2" "geonav_transform" "tf2_geometry_msgs")
set(antobot_heading_TEST_DEPENDS )
set(antobot_heading_DOC_DEPENDS )
set(antobot_heading_URL_WEBSITE "")
set(antobot_heading_URL_BUGTRACKER "")
set(antobot_heading_URL_REPOSITORY "")
set(antobot_heading_DEPRECATED "")