set(_CATKIN_CURRENT_PACKAGE "antobot_base")
set(antobot_base_VERSION "0.0.1")
set(antobot_base_MAINTAINER "Daniel Freer <daniel.freer@antobot.ai>")
set(antobot_base_PACKAGE_FORMAT "1")
set(antobot_base_BUILD_DEPENDS "hardware_interface" "controller_manager" "roscpp" "control_msgs" "trajectory_msgs" "actionlib" "pluginlib" "transmission_interface" "urdf" "control_toolbox" "joint_limits_interface" "std_msgs" "message_generation" "antobot_msgs")
set(antobot_base_BUILD_EXPORT_DEPENDS "message_runtime" "hardware_interface" "controller_manager" "ros_controllers" "roscpp" "control_msgs" "trajectory_msgs" "actionlib" "pluginlib" "transmission_interface" "urdf" "control_toolbox" "joint_limits_interface" "std_msgs" "antobot_msgs")
set(antobot_base_BUILDTOOL_DEPENDS "catkin")
set(antobot_base_BUILDTOOL_EXPORT_DEPENDS )
set(antobot_base_EXEC_DEPENDS "message_runtime" "hardware_interface" "controller_manager" "ros_controllers" "roscpp" "control_msgs" "trajectory_msgs" "actionlib" "pluginlib" "transmission_interface" "urdf" "control_toolbox" "joint_limits_interface" "std_msgs" "antobot_msgs")
set(antobot_base_RUN_DEPENDS "message_runtime" "hardware_interface" "controller_manager" "ros_controllers" "roscpp" "control_msgs" "trajectory_msgs" "actionlib" "pluginlib" "transmission_interface" "urdf" "control_toolbox" "joint_limits_interface" "std_msgs" "antobot_msgs")
set(antobot_base_TEST_DEPENDS )
set(antobot_base_DOC_DEPENDS )
set(antobot_base_URL_WEBSITE "")
set(antobot_base_URL_BUGTRACKER "")
set(antobot_base_URL_REPOSITORY "")
set(antobot_base_DEPRECATED "")