###########################################################################################################################
# Copyright (c) 2023, ANTOBOT LTD.
# All rights reserved.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

# Code Description:     Defines the parameters for filtering the laser data from the lidar.

# Contact:        soyoung.kim@antobot.ai

# # # #  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

##################################################################################################################

scan_filter_chain:
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 0.2 #minimum range
    upper_threshold: 10 #maximum range for dark object
    lower_replacement_value: -.inf
    upper_replacement_value: .inf
- name: range1
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 0
    upper_angle: 0.5
- name: range2
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -0.5
    upper_angle: 0
