set(_CATKIN_CURRENT_PACKAGE "antobot_tel_key")
set(antobot_tel_key_VERSION "0.0.0")
set(antobot_tel_key_MAINTAINER "Daniel Freer <daniel.freer@antobot.ai>")
set(antobot_tel_key_PACKAGE_FORMAT "2")
set(antobot_tel_key_BUILD_DEPENDS "control_msgs" "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "trajectory_msgs")
set(antobot_tel_key_BUILD_EXPORT_DEPENDS "control_msgs" "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "trajectory_msgs")
set(antobot_tel_key_BUILDTOOL_DEPENDS "catkin")
set(antobot_tel_key_BUILDTOOL_EXPORT_DEPENDS )
set(antobot_tel_key_EXEC_DEPENDS "control_msgs" "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "trajectory_msgs")
set(antobot_tel_key_RUN_DEPENDS "control_msgs" "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "trajectory_msgs")
set(antobot_tel_key_TEST_DEPENDS )
set(antobot_tel_key_DOC_DEPENDS )
set(antobot_tel_key_URL_WEBSITE "")
set(antobot_tel_key_URL_BUGTRACKER "")
set(antobot_tel_key_URL_REPOSITORY "")
set(antobot_tel_key_DEPRECATED "")