# Copyright (c) 2023, ANTOBOT LTD.
# All rights reserved.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# # # Code Description: This example configuration file includes robot specific information. Make a copy of this file in the 
#                       same directory (antobot_description/config) with file name of platform_config.yaml
#                       This file is included in github repository.

# Author:       soyoung.kim@antobot.ai
# # # #  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

## High-level configuration

robot_hardware: True
robot_platform: "ant"  
robot_version: 4
robot_role: "platform"
location: "uk"



## Sensor information

lidar:
  c16:    # Front lidar
    px: 0.683
    py: 0.0
    pz: 1.1
    r: 0
    p: 0
    y: 2.35
    mode: "navigation"
    location: "front"

    device_ip: 192.168.1.200 
    msop_port: 2368
    difop_port: 2369    

camera:
  zed:
    # need to be updated
    px: 0.683
    py: 0.0
    pz: 1.1
    r: 0
    p: 0
    y: 2.35

    mode: "recording"
    location: "left"

    device_ip: 192.168.1.103

  RP:
    # need to be updated
    px: 0.683
    py: 0.0
    pz: 1.1
    r: 0
    p: 0
    y: 2.35

    mode: "recording"
    location: "left"

    device_ip: 192.168.1.105

gps:
  urcu:
    px: 0.683
    py: 0.0
    pz: 1.41
    r: 0
    p: 0
    y: 0
    mode: "navigation"

    device_port: "/dev/ttyTHS0"
    rtk_type: "ntrip"   #ppp or ntrip or ant_mqtt
    #time_zone: "UKsummer"  #todo


imu:
  urcu:
    px: -0.1146
    py: -0.01941
    pz: 0.1832
    r: 0
    p: 0
    y: 0
    mode: "navigation"
    switch: True
  xsens:
    px: 0
    py: 0
    pz: 0
    r: 0
    p: 0
    y: 0
    mode: "record"
    switch: False


