set(_CATKIN_CURRENT_PACKAGE "antobot_datamanager")
set(antobot_datamanager_VERSION "0.0.0")
set(antobot_datamanager_MAINTAINER "will <will@todo.todo>")
set(antobot_datamanager_PACKAGE_FORMAT "2")
set(antobot_datamanager_BUILD_DEPENDS "message_generation" "std_msgs" "geometry_msgs" "roscpp" "rospy")
set(antobot_datamanager_BUILD_EXPORT_DEPENDS )
set(antobot_datamanager_BUILDTOOL_DEPENDS "catkin")
set(antobot_datamanager_BUILDTOOL_EXPORT_DEPENDS )
set(antobot_datamanager_EXEC_DEPENDS "message_runtime" "std_msgs" "geometry_msgs" "roscpp" "rospy")
set(antobot_datamanager_RUN_DEPENDS "message_runtime" "std_msgs" "geometry_msgs" "roscpp" "rospy")
set(antobot_datamanager_TEST_DEPENDS )
set(antobot_datamanager_DOC_DEPENDS )
set(antobot_datamanager_URL_WEBSITE "")
set(antobot_datamanager_URL_BUGTRACKER "")
set(antobot_datamanager_URL_REPOSITORY "")
set(antobot_datamanager_DEPRECATED "")