set(antobot_datamanager_SETUP_PY_SETUP_MODULE "distutils.core")
set(antobot_datamanager_SETUP_PY_VERSION "0.0.0")
set(antobot_datamanager_SETUP_PY_SCRIPTS "")
set(antobot_datamanager_SETUP_PY_PACKAGES "antobot_datamanager")
set(antobot_datamanager_SETUP_PY_PACKAGE_DIRS "src/antobot_datamanager")
set(antobot_datamanager_SETUP_PY_MODULES "")
set(antobot_datamanager_SETUP_PY_MODULE_DIRS "")